### ISSUE TITLE
Definition of ℙ?

### ISSUE THREAD

**Issue by tomtomjhj** [KAIST-IS593/is593-2020-spring#12]
I think `ℙ = AllocaSite × 𝕀` so that every `alloca` in `b1` yields the same ptr in each iteration.
```c
while (1) {
    int i;
}
```
```llvm
b1:
    %i = alloca i32
    br label %b1
```

But the specification suggests that it might not be the case. What is the correct definition of ℙ?

> Memory is allocated; a pointer is returned. The allocated memory is uninitialized, and loading from uninitialized memory produces an undefined value. The operation itself is undefined if there is insufficient stack space for the allocation.’alloca’d memory is automatically released when the function returns. The ‘alloca’ instruction is commonly used to represent automatic variables that must have an address available. **When the function returns (either with the ret or resume instructions), the memory is reclaimed**. Allocating zero bytes is legal, but the returned pointer may not be unique. The order in which memory is allocated (ie., which way the stack grows) is not specified.
https://llvm.org/docs/LangRef.html#id201

**Comment by KihongHeo** [comment]
Assume that `P = AllocaSite`. Here `I` is unnecessary because it is not a dynamic allocation. As you mentioned, only a single memory cell is allocated during the loop.

In principle, this is the same as local variable. 
`When the function returns (either with the ret or resume instructions), the memory is reclaimed`
That means after returns, the memory cell is meaningless and illegal that is also true for local variable. But in our concrete semantics, we just omit that part. Someone can also design more machine-like concrete semantics: after return, remove all the local things (local var and alloca) from the memory.

**Comment by tomtomjhj** [comment]
I think we still need 𝕀 for ℙ just like 𝕏 needs 𝕀.

**Comment by KihongHeo** [comment]
Oh, you mean the concrete domain. Sorry for confusion.
Yes. You are right. It is the same as X.
P# is just "alloca-site."
