### ISSUE TITLE
[Homework 4] callgraph information to Semantics.filter

### ISSUE THREAD

**Issue by KunJeong** [KAIST-IS593/is593-2020-spring#20]
Hi.
Currently, the Semantics.filter function has signature `Llvm.llvalue -> bool -> Memory.t -> Memory.t`. However, since the function applies update based on the predicate, it seems like it might need the callgraph information to determine whether it should apply strong update or weak update.
What am I missing here?
Thank you.

**Comment by KihongHeo** [comment]
Hi,
How do you define "weak" filter?
I think this is not a fundamental issue but an implementation design choice. I guess you can implement your strategy in `transfer` rather than `filter`.

**Comment by KunJeong** [comment]
Ah. You're right, weak update makes no sense since the output memory should be smaller than the input. Somehow I thought that filter was also a kind of assignment. Thank you for the correction.

**Comment by KunJeong** [comment]
I just realized I had been confusing the new strong/weak update with the original update for assignment/filter the whole time.
So to be clear, there are two versions of update: one that always applies strong update for **Assign** and `filter`, another that applies strong or weak update for **store** instructions.
And in the quiz I have to state which cases strong update is applicable for **store** instructions.
Am I correct?

**Comment by KihongHeo** [comment]
Strong/weak update strategy is not determined by instruction type.
Let us recall the principle. Strong update is applicable only when the concretization of the abstract memory location contains only one element. Otherwise, we should do weak update.

Indirect assignments (store, as you mentioned) should be handled with weak update but this is not the only case in our setting. Because of the presence of function call and context abstraction, there exist also other cases that require weak update. In a naive design, you have to apply weak update for all local variables because of the context abstraction. But in some cases, we can avoid this serious precision loss and apply strong update. This is what the quiz asks.

**Comment by KunJeong** [comment]
I think I understand now. Thank you.
