### ISSUE TITLE
[Project] Announcements

### ISSUE THREAD

**Issue by KihongHeo** [KAIST-IS593/is593-2020-spring#37]
Hi all,

I hope you enjoy your project. The project is due on this Sunday. Here are some announcement.

### Submission 
Please submit the following things in your private repository:

- Source code
- README.md: brief description about your info (name + student id), prerequisites, build commands, run commands, etc
- test examples: under the `test` directory + test commands
- Proposal and slides (pdf files): under the `doc` directory.

For slides, it is okey to upload after your presentation.

### Presentation: 10 min + 3 min QnA
Please prepare a microphone and a camera. I will give you access to screen share.

### Evaluation
Below is the evaluation sheet:

- Motivation & Problem:
  * Is the problem well-motivated? [0-5]
  * Is the problem well-designed? [0-5]
  * Is the problem novel? [0-5]

- Approach & Result:
  * Is the approach complete? [0-5]
  * Are the results significant? [0-5]
  * Is the approach promising? [0-5]

- Presentation:
  * Is the flow logical and interesting? [0-5]
  * Are the speech and slides clear and readable? [0-5]
  * Are questions answered clearly? [0-5]

**Comment by hyunsikjeong** [comment]
@KihongHeo 
It seems project presentations are on 6/17, 6/22 and 6/24, as the second slide of the project slides.
However, speakers will be randomly chosen each day of 6/15, 6/17 and 6/22, as the last slide.
Then, is there no presentations tomorrow but choosing speakers for the next class?

I left a comment because I'm not sure it's better to make a new issue about this.

**Comment by KihongHeo** [comment]
Right. That was a typo.

Tomorrow, there is no presentations by students.
